// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package user

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUser = `-- name: AddUser :one
INSERT INTO account.users (
    username,
    email,
    password_hash,
    coins
)
VALUES (
$1,
$2,
$3,
$4
) RETURNING id
`

type AddUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Coins        int64  `json:"coins"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, addUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Coins,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    username,
    email,
    password_hash,
    coins
FROM account.users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Coins        int64       `json:"coins"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Coins,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, coins
FROM account.users WHERE id = $1
`

type GetUserByIDRow struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
	Coins    int64       `json:"coins"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Coins,
	)
	return i, err
}
