// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package user

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUser = `-- name: AddUser :one
INSERT INTO users.users (
    username,
    email,
    password_hash,
    coins
)
VALUES (
$1,
$2,
$3,
$4
) RETURNING id
`

type AddUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Coins        int64  `json:"coins"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, addUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Coins,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    username,
    email,
    password_hash,
    coins
FROM users.users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Coins        int64       `json:"coins"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Coins,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.username, u.email, u.coins, s.current_streak
FROM users.users u JOIN users.user_streaks s
ON u.id = s.user_id
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID            pgtype.UUID `json:"id"`
	Username      string      `json:"username"`
	Email         string      `json:"email"`
	Coins         int64       `json:"coins"`
	CurrentStreak int32       `json:"current_streak"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Coins,
		&i.CurrentStreak,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, username
FROM users.users
WHERE id = ANY($1::uuid[])
`

type GetUsersByIDsRow struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
}

func (q *Queries) GetUsersByIDs(ctx context.Context, ids []pgtype.UUID) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByIDsRow
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoins = `-- name: UpdateCoins :one
UPDATE users.users
SET coins = coins + $1
WHERE id = $2
  AND coins + $1 >= 0
RETURNING coins
`

type UpdateCoinsParams struct {
	DeltaCoins int64       `json:"delta_coins"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateCoins(ctx context.Context, arg UpdateCoinsParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateCoins, arg.DeltaCoins, arg.UserID)
	var coins int64
	err := row.Scan(&coins)
	return coins, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1
    FROM users.users
    WHERE id = $1
)
`

func (q *Queries) UserExists(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
