services:
  pets:
    image: pets
    env_file:
      - ./backend/pets/.env.example
    build:
      context: .
      dockerfile: ./backend/pets/Dockerfile
    restart: unless-stopped
    depends_on:
      pets-postgres:
        condition: service_healthy
    ports:
      - "8082:8080"
    
  users:
    image: users
    env_file:
      - .env.example
    hostname: users
    build:
      context: .
      dockerfile: ./backend/user/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  tasks:
    image: tasks
    hostname: tasks
    env_file:
      - .env.example
    build:
      context: .
      dockerfile: ./backend/tasks/Dockerfile
    restart: unless-stopped
    depends_on:
      tasks-postgres:
        condition: service_healthy
    environment:
      HTTP_ADDR: :8080
      DATABASE_DSN: postgres://tasks_user:12345@tasks-postgres:5432/tasks?sslmode=disable
    ports:
      - "8081:8080"

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_PORT: "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "port=5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_user -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  tasks-postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: "tasks"
      POSTGRES_USER: "tasks_user"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_PORT: "5432"
    volumes:
      - tasks-postgres-data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "port=5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tasks_user -d tasks" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  pets-postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: "pet_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5434:5432"
    volumes:
      - pets-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg_user -d pet_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate-pets-postgres:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/pets/migrations:/migrations
    command:
      [
        "-path=/migrations",
        "-database=postgres://user:password@pets-postgres:5432/pet_db?sslmode=disable",
        "up"
      ]

volumes:
  postgres-data:
  tasks-postgres-data:
  pets-postgres-data: