// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package token

import (
	"context"
)

type Querier interface {
	AddToken(ctx context.Context, arg AddTokenParams) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (UsersRefreshToken, error)
}

var _ Querier = (*Queries)(nil)
