// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package streak

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStreakByUserIDForUpdate = `-- name: GetStreakByUserIDForUpdate :one
SELECT user_id, current_streak, last_active_date
FROM users.user_streaks
WHERE user_id = $1
FOR UPDATE
`

type GetStreakByUserIDForUpdateRow struct {
	UserID         pgtype.UUID `json:"user_id"`
	CurrentStreak  int32       `json:"current_streak"`
	LastActiveDate pgtype.Date `json:"last_active_date"`
}

func (q *Queries) GetStreakByUserIDForUpdate(ctx context.Context, userID pgtype.UUID) (GetStreakByUserIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getStreakByUserIDForUpdate, userID)
	var i GetStreakByUserIDForUpdateRow
	err := row.Scan(&i.UserID, &i.CurrentStreak, &i.LastActiveDate)
	return i, err
}

const updateStreak = `-- name: UpdateStreak :exec
INSERT INTO users.user_streaks (
    user_id, current_streak, last_active_date
)
VALUES (
$1,
   $2,
   $3
)
ON CONFLICT (user_id) DO UPDATE
    SET current_streak = $2,
    last_active_date = $3
    RETURNING current_streak, last_active_date
`

type UpdateStreakParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	CurrentStreak  int32       `json:"current_streak"`
	LastActiveDate pgtype.Date `json:"last_active_date"`
}

func (q *Queries) UpdateStreak(ctx context.Context, arg UpdateStreakParams) error {
	_, err := q.db.Exec(ctx, updateStreak, arg.UserID, arg.CurrentStreak, arg.LastActiveDate)
	return err
}
