// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package streak

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetStreakByUserID(ctx context.Context, userID pgtype.UUID) (GetStreakByUserIDRow, error)
	GetStreakByUserIDForUpdate(ctx context.Context, userID pgtype.UUID) (GetStreakByUserIDForUpdateRow, error)
	UpdateStreak(ctx context.Context, arg UpdateStreakParams) error
}

var _ Querier = (*Queries)(nil)
