// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package sqlctask

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserTasksBatch = `-- name: CreateUserTasksBatch :many
WITH existing_tasks AS (
    SELECT t.id, 
    t.title, 
    t.description, 
    t.reward_coins, 
    t.reward_xp,
    t.task_type,
    ut.status,
    ut.completed_at
    FROM user_tasks ut
    JOIN tasks t ON t.id = ut.task_id 
    WHERE ut.user_id = $1::uuid
      AND ut.updated_at >= CURRENT_DATE 
      AND ut.updated_at < CURRENT_DATE + INTERVAL '1 day'
),
random_tasks AS (
    SELECT t.id, t.title, t.description, t.reward_coins, t.reward_xp, t.task_type, 'active'::text AS status, null::timestamptz as completed_at
    FROM tasks t
    WHERE NOT EXISTS (SELECT 1 FROM existing_tasks)
    ORDER BY RANDOM()
    LIMIT $2::int
)
SELECT id, title, description, reward_coins, reward_xp, task_type, status, completed_at, (NOT EXISTS (SELECT 1 FROM existing_tasks))::bool AS is_new
FROM existing_tasks
UNION ALL
SELECT id, title, description, reward_coins, reward_xp, task_type, status, completed_at, true AS is_new
FROM random_tasks
`

type CreateUserTasksBatchParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	RandomLimit int32       `json:"random_limit"`
}

type CreateUserTasksBatchRow struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	RewardCoins int32              `json:"reward_coins"`
	RewardXp    int64              `json:"reward_xp"`
	TaskType    pgtype.Text        `json:"task_type"`
	Status      string             `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	IsNew       bool               `json:"is_new"`
}

func (q *Queries) CreateUserTasksBatch(ctx context.Context, arg CreateUserTasksBatchParams) ([]CreateUserTasksBatchRow, error) {
	rows, err := q.db.Query(ctx, createUserTasksBatch, arg.UserID, arg.RandomLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateUserTasksBatchRow
	for rows.Next() {
		var i CreateUserTasksBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.RewardCoins,
			&i.RewardXp,
			&i.TaskType,
			&i.Status,
			&i.CompletedAt,
			&i.IsNew,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findByIDForUser = `-- name: FindByIDForUser :one
SELECT
    t.id,
    t.title,
    t.description,
    t.reward_coins,
    t.reward_xp,
    t.task_type,
    COALESCE(ut.status, 'active')::text AS status,
    ut.completed_at
FROM tasks t
LEFT JOIN user_tasks ut ON ut.task_id = t.id AND ut.user_id = $1
WHERE t.id = $2
`

type FindByIDForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type FindByIDForUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	RewardCoins int32              `json:"reward_coins"`
	RewardXp    int64              `json:"reward_xp"`
	TaskType    pgtype.Text        `json:"task_type"`
	Status      string             `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) FindByIDForUser(ctx context.Context, arg FindByIDForUserParams) (FindByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, findByIDForUser, arg.UserID, arg.ID)
	var i FindByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.RewardCoins,
		&i.RewardXp,
		&i.TaskType,
		&i.Status,
		&i.CompletedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, title, description, reward_coins, reward_xp, task_type
FROM tasks
WHERE id = $1::uuid
`

type GetTaskByIDRow struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	RewardCoins int32       `json:"reward_coins"`
	RewardXp    int64       `json:"reward_xp"`
	TaskType    pgtype.Text `json:"task_type"`
}

func (q *Queries) GetTaskByID(ctx context.Context, dollar_1 pgtype.UUID) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, dollar_1)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.RewardCoins,
		&i.RewardXp,
		&i.TaskType,
	)
	return i, err
}

const getTodayCompletedTasksForUser = `-- name: GetTodayCompletedTasksForUser :many
SELECT 
    t.id,
    t.title,
    t.reward_coins,
    t.reward_xp,
    t.finished_desc,
    ut.updated_at 
FROM user_tasks ut
join tasks t on t.id = ut.task_id 
WHERE ut.user_id = $1 AND ut.updated_at >= CURRENT_DATE AND 
ut.updated_at < CURRENT_DATE + INTERVAL '1 day' AND ut.status = 'completed'
`

type GetTodayCompletedTasksForUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	RewardCoins  int32              `json:"reward_coins"`
	RewardXp     int64              `json:"reward_xp"`
	FinishedDesc string             `json:"finished_desc"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTodayCompletedTasksForUser(ctx context.Context, userID pgtype.UUID) ([]GetTodayCompletedTasksForUserRow, error) {
	rows, err := q.db.Query(ctx, getTodayCompletedTasksForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTodayCompletedTasksForUserRow
	for rows.Next() {
		var i GetTodayCompletedTasksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.RewardCoins,
			&i.RewardXp,
			&i.FinishedDesc,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTaskForUpdate = `-- name: GetUserTaskForUpdate :one
SELECT
    ut.status,
    ut.completed_at,

    t.id,
    t.title,
    t.description,
    t.reward_coins,
    t.reward_xp,
    t.task_type
FROM user_tasks ut
JOIN tasks t ON t.id = ut.task_id
WHERE ut.user_id = $1
  AND ut.task_id = $2
FOR UPDATE OF ut
`

type GetUserTaskForUpdateParams struct {
	UserID pgtype.UUID `json:"user_id"`
	TaskID pgtype.UUID `json:"task_id"`
}

type GetUserTaskForUpdateRow struct {
	Status      string             `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	RewardCoins int32              `json:"reward_coins"`
	RewardXp    int64              `json:"reward_xp"`
	TaskType    pgtype.Text        `json:"task_type"`
}

func (q *Queries) GetUserTaskForUpdate(ctx context.Context, arg GetUserTaskForUpdateParams) (GetUserTaskForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserTaskForUpdate, arg.UserID, arg.TaskID)
	var i GetUserTaskForUpdateRow
	err := row.Scan(
		&i.Status,
		&i.CompletedAt,
		&i.ID,
		&i.Title,
		&i.Description,
		&i.RewardCoins,
		&i.RewardXp,
		&i.TaskType,
	)
	return i, err
}

const insertUserTasksBatch = `-- name: InsertUserTasksBatch :exec
INSERT INTO user_tasks (user_id, task_id)
SELECT 
    $1::uuid AS user_id, 
    unnest($2::uuid[]) AS task_id
`

type InsertUserTasksBatchParams struct {
	UserID  pgtype.UUID   `json:"user_id"`
	TaskIds []pgtype.UUID `json:"task_ids"`
}

func (q *Queries) InsertUserTasksBatch(ctx context.Context, arg InsertUserTasksBatchParams) error {
	_, err := q.db.Exec(ctx, insertUserTasksBatch, arg.UserID, arg.TaskIds)
	return err
}

const updateUserTaskCompleted = `-- name: UpdateUserTaskCompleted :exec
UPDATE user_tasks ut
SET
    status = 'completed',
    completed_at = NOW(),
    updated_at = NOW()
WHERE ut.user_id = $1
  AND ut.task_id = $2
  AND ut.updated_at >= CURRENT_DATE AND 
ut.updated_at < CURRENT_DATE + INTERVAL '1 day'
`

type UpdateUserTaskCompletedParams struct {
	UserID pgtype.UUID `json:"user_id"`
	TaskID pgtype.UUID `json:"task_id"`
}

func (q *Queries) UpdateUserTaskCompleted(ctx context.Context, arg UpdateUserTaskCompletedParams) error {
	_, err := q.db.Exec(ctx, updateUserTaskCompleted, arg.UserID, arg.TaskID)
	return err
}
