// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlctask

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	FindByIDForUser(ctx context.Context, arg FindByIDForUserParams) (FindByIDForUserRow, error)
	GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error)
	GetUserTaskForUpdate(ctx context.Context, arg GetUserTaskForUpdateParams) (GetUserTaskForUpdateRow, error)
	InsertUserTaskCompleted(ctx context.Context, arg InsertUserTaskCompletedParams) error
	ListRandomTasksForUser(ctx context.Context, userID pgtype.UUID) ([]ListRandomTasksForUserRow, error)
	UpdateUserTaskCompleted(ctx context.Context, arg UpdateUserTaskCompletedParams) error
}

var _ Querier = (*Queries)(nil)
