// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlctask

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUserTasksBatch(ctx context.Context, arg CreateUserTasksBatchParams) error
	FindByIDForUser(ctx context.Context, arg FindByIDForUserParams) (FindByIDForUserRow, error)
	GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error)
	// RETURNING user_id, task_id, updated_at;
	GetUserTaskForUpdate(ctx context.Context, arg GetUserTaskForUpdateParams) (GetUserTaskForUpdateRow, error)
	InsertUserTaskCompleted(ctx context.Context, arg InsertUserTaskCompletedParams) error
	ListRandomTasksForUser(ctx context.Context, limit int32) ([]ListRandomTasksForUserRow, error)
	UpdateUserTaskCompleted(ctx context.Context, arg UpdateUserTaskCompletedParams) error
}

var _ Querier = (*Queries)(nil)
