// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package reward

import (
	"database/sql/driver"
	"fmt"
)

type UsersRewardStatus string

const (
	UsersRewardStatusActive   UsersRewardStatus = "active"
	UsersRewardStatusRedeemed UsersRewardStatus = "redeemed"
)

func (e *UsersRewardStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRewardStatus(s)
	case string:
		*e = UsersRewardStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRewardStatus: %T", src)
	}
	return nil
}

type NullUsersRewardStatus struct {
	UsersRewardStatus UsersRewardStatus `json:"users_reward_status"`
	Valid             bool              `json:"valid"` // Valid is true if UsersRewardStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRewardStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRewardStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRewardStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRewardStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRewardStatus), nil
}

type UsersRewardDefinition struct {
	ID          int32  `json:"id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
}
