// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package reward

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUserReward(ctx context.Context, arg AddUserRewardParams) (AddUserRewardRow, error)
	GetActiveRewardsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetActiveRewardsByUserIDRow, error)
	GetRewardByUserIDAndRewardID(ctx context.Context, arg GetRewardByUserIDAndRewardIDParams) (GetRewardByUserIDAndRewardIDRow, error)
	GetRewardDefinitionByCode(ctx context.Context, code string) (UsersRewardDefinition, error)
	GetRewardDefinitions(ctx context.Context) ([]UsersRewardDefinition, error)
	GetRewardsByUserIDAndPeriod(ctx context.Context, arg GetRewardsByUserIDAndPeriodParams) ([]GetRewardsByUserIDAndPeriodRow, error)
	GetUserRewardsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetUserRewardsByUserIDRow, error)
	RedeemUserReward(ctx context.Context, arg RedeemUserRewardParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
