// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package reward

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserReward = `-- name: AddUserReward :one
INSERT INTO users.user_rewards (
    user_id, reward_id,
    promo_code, expires_at
)
VALUES (
       $1,
       $2,
       $3,
       $4
       )
RETURNING id, user_id, promo_code, status, redeemed_at, expires_at
`

type AddUserRewardParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RewardID  int32              `json:"reward_id"`
	PromoCode string             `json:"promo_code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type AddUserRewardRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	PromoCode  string             `json:"promo_code"`
	Status     UsersRewardStatus  `json:"status"`
	RedeemedAt pgtype.Timestamptz `json:"redeemed_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) AddUserReward(ctx context.Context, arg AddUserRewardParams) (AddUserRewardRow, error) {
	row := q.db.QueryRow(ctx, addUserReward,
		arg.UserID,
		arg.RewardID,
		arg.PromoCode,
		arg.ExpiresAt,
	)
	var i AddUserRewardRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PromoCode,
		&i.Status,
		&i.RedeemedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getActiveRewardsByUserID = `-- name: GetActiveRewardsByUserID :many
SELECT ur.id, ur.user_id, ur.promo_code,
       rd.name, rd.description,
       ur.status, ur.redeemed_at,
       ur.expires_at
FROM users.user_rewards ur JOIN users.reward_definitions rd
                                ON ur.reward_id = rd.id
WHERE user_id = $1
  AND status = 'active'
  AND (
        ur.expires_at IS NULL OR ur.expires_at > NOW()
    )
ORDER BY ur.created_at DESC
`

type GetActiveRewardsByUserIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	PromoCode   string             `json:"promo_code"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Status      UsersRewardStatus  `json:"status"`
	RedeemedAt  pgtype.Timestamptz `json:"redeemed_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetActiveRewardsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetActiveRewardsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getActiveRewardsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveRewardsByUserIDRow
	for rows.Next() {
		var i GetActiveRewardsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PromoCode,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.RedeemedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRewardByUserIDAndRewardID = `-- name: GetRewardByUserIDAndRewardID :one
SELECT ur.id, ur.user_id, ur.promo_code,
       rd.name, rd.description,
       ur.status, ur.redeemed_at,
       ur.expires_at
FROM users.user_rewards ur JOIN users.reward_definitions rd
                                ON ur.reward_id = rd.id
WHERE ur.id = $1 AND ur.user_id = $2
`

type GetRewardByUserIDAndRewardIDParams struct {
	RewardID pgtype.UUID `json:"reward_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

type GetRewardByUserIDAndRewardIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	PromoCode   string             `json:"promo_code"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Status      UsersRewardStatus  `json:"status"`
	RedeemedAt  pgtype.Timestamptz `json:"redeemed_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetRewardByUserIDAndRewardID(ctx context.Context, arg GetRewardByUserIDAndRewardIDParams) (GetRewardByUserIDAndRewardIDRow, error) {
	row := q.db.QueryRow(ctx, getRewardByUserIDAndRewardID, arg.RewardID, arg.UserID)
	var i GetRewardByUserIDAndRewardIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PromoCode,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.RedeemedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getRewardDefinitionByCode = `-- name: GetRewardDefinitionByCode :one
SELECT
    id, code, name, description
FROM users.reward_definitions
WHERE code = $1
`

func (q *Queries) GetRewardDefinitionByCode(ctx context.Context, code string) (UsersRewardDefinition, error) {
	row := q.db.QueryRow(ctx, getRewardDefinitionByCode, code)
	var i UsersRewardDefinition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getUserRewardsByUserID = `-- name: GetUserRewardsByUserID :many
SELECT
    ur.id, ur.user_id, ur.promo_code,
    rd.name, rd.description,
    ur.status, ur.redeemed_at,
    ur.expires_at
FROM users.user_rewards AS ur
         JOIN users.reward_definitions AS rd
              ON rd.id = ur.reward_id
WHERE ur.user_id = $1
ORDER BY ur.created_at DESC
`

type GetUserRewardsByUserIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	PromoCode   string             `json:"promo_code"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Status      UsersRewardStatus  `json:"status"`
	RedeemedAt  pgtype.Timestamptz `json:"redeemed_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetUserRewardsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetUserRewardsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getUserRewardsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRewardsByUserIDRow
	for rows.Next() {
		var i GetUserRewardsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PromoCode,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.RedeemedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemUserReward = `-- name: RedeemUserReward :one
UPDATE users.user_rewards
SET
    status = 'redeemed',
    redeemed_at = NOW()
WHERE promo_code = $1
    AND user_id = $2
    AND status = 'active'
    AND (
        expires_at IS NULL
        OR expires_at > NOW()
    )
RETURNING id
`

type RedeemUserRewardParams struct {
	PromoCode string      `json:"promo_code"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RedeemUserReward(ctx context.Context, arg RedeemUserRewardParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, redeemUserReward, arg.PromoCode, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
