// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package event

import (
	"database/sql/driver"
	"fmt"
)

type UsersEventType string

const (
	UsersEventTypeStreakReward UsersEventType = "streak_reward"
	UsersEventTypeNewReward    UsersEventType = "new_reward"
)

func (e *UsersEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersEventType(s)
	case string:
		*e = UsersEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersEventType: %T", src)
	}
	return nil
}

type NullUsersEventType struct {
	UsersEventType UsersEventType `json:"users_event_type"`
	Valid          bool           `json:"valid"` // Valid is true if UsersEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersEventType) Scan(value interface{}) error {
	if value == nil {
		ns.UsersEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersEventType), nil
}
