// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package event

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserEvent = `-- name: AddUserEvent :exec
INSERT INTO users.user_events (
    user_id, type,
    xp, coins,
    streak, user_reward_id)
VALUES (
           $1,$2,
           $3,$4,
           $5, $6
)
`

type AddUserEventParams struct {
	UserID       pgtype.UUID    `json:"user_id"`
	Type         UsersEventType `json:"type"`
	Xp           int32          `json:"xp"`
	Coins        int32          `json:"coins"`
	Streak       pgtype.Int4    `json:"streak"`
	UserRewardID pgtype.UUID    `json:"user_reward_id"`
}

func (q *Queries) AddUserEvent(ctx context.Context, arg AddUserEventParams) error {
	_, err := q.db.Exec(ctx, addUserEvent,
		arg.UserID,
		arg.Type,
		arg.Xp,
		arg.Coins,
		arg.Streak,
		arg.UserRewardID,
	)
	return err
}

const deleteDeliveredEvents = `-- name: DeleteDeliveredEvents :exec
DELETE FROM users.user_events
       WHERE delivered_at IS NOT NULL
        AND delivered_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteDeliveredEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteDeliveredEvents)
	return err
}

const getUserEventsAndMarkDelivered = `-- name: GetUserEventsAndMarkDelivered :many
UPDATE users.user_events AS ue
SET delivered_at = NOW()
WHERE ue.id IN (
    SELECT e.id FROM users.user_events AS e
    WHERE e.user_id = $1 AND e.delivered_at IS NULL
    ORDER BY e.created_at ASC
)
    RETURNING ue.id, ue.user_id, ue.type, ue.xp,
    ue.coins, ue.streak, ue.user_reward_id, ue.created_at
`

type GetUserEventsAndMarkDeliveredRow struct {
	ID           int64              `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Type         UsersEventType     `json:"type"`
	Xp           int32              `json:"xp"`
	Coins        int32              `json:"coins"`
	Streak       pgtype.Int4        `json:"streak"`
	UserRewardID pgtype.UUID        `json:"user_reward_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserEventsAndMarkDelivered(ctx context.Context, userID pgtype.UUID) ([]GetUserEventsAndMarkDeliveredRow, error) {
	rows, err := q.db.Query(ctx, getUserEventsAndMarkDelivered, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserEventsAndMarkDeliveredRow
	for rows.Next() {
		var i GetUserEventsAndMarkDeliveredRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Xp,
			&i.Coins,
			&i.Streak,
			&i.UserRewardID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
