// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package event

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUserEvent(ctx context.Context, arg AddUserEventParams) error
	DeleteDeliveredEvents(ctx context.Context) error
	GetUserEventsAndMarkDelivered(ctx context.Context, userID pgtype.UUID) ([]GetUserEventsAndMarkDeliveredRow, error)
}

var _ Querier = (*Queries)(nil)
