// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package token

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UsersRefreshToken struct {
	ID        int64              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
