// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package token

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToken = `-- name: AddToken :exec
INSERT INTO account.refresh_tokens (
    user_id,
    token_hash,
    expires_at
)
VALUES (
           $1,
           $2,
           $3
       )
`

type AddTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) AddToken(ctx context.Context, arg AddTokenParams) error {
	_, err := q.db.Exec(ctx, addToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM account.refresh_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
DELETE FROM account.refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, tokenHash)
	return err
}

const getRefreshTokenByHashForUpdate = `-- name: GetRefreshTokenByHashForUpdate :one
SELECT
    id,
    user_id,
    token_hash,
    expires_at,
    created_at
FROM account.refresh_tokens
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (AccountRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHashForUpdate, tokenHash)
	var i AccountRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
